name: "Publish custom ktlint rules to the GitHub Packages"
on:
  push:
    branches:
      - main
    paths:
      - 'custom-rules/src/main/java/com/horie1024/custom_rules/**.kt'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish custom ktlint rules
        env:
          USERNAME: horie1024
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build publish
